version: "3.9"

services:
  web:
    build: flask-app/
    volumes:
      - './flask-app:/code'
      - './secrets:/secrets'
    restart: unless-stopped
    ports:
      - "8001:4000"
    depends_on:
      - db

  db:
    build: db/
    volumes:
      - ./sqlite_db:/data
