PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS slots;

CREATE TABLE slots (
    slotID INTEGER PRIMARY KEY AUTOINCREMENT,
    startTime DATETIME NOT NULL,
    endTime DATETIME NOT NULL,
    sport TEXT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    subSection TEXT CHECK (subSection IN ('1A', '1B', '2A', '2B')) NOT NULL
);
